dappx/urls.py
from django.conf.urls import url
from dappx import views
# SET THE NAMESPACE!
app_name = 'dappx'
# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    url(r'^register/$',views.register,name='register'),
    url(r'^user_login/$',views.user_login,name='user_login'),
]

dprojx/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from dappx import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',views.index,name='index'),
    url(r'^special/',views.special,name='special'),
    url(r'^dappx/',include('dappx.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
]

dappx/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)
    def __str__(self):
      return self.user.username
# Create your models here.

class LogFile(models.Model):
    LogPath = models.CharField(max_length=512)
    FileName = models.CharField(max_length=512)
    PostedDate = models.DateField(auto_now_add=True)
    PostedBy = models.ForeignKey(User, on_delete=models.CASCADE)
    AnalyzeStatus = models.CharField(max_length=20)

dappx/forms.py
from django import forms
from dappx.models import UserProfileInfo
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','password','email')

class UserProfileInfoForm(forms.ModelForm):
     class Meta():
         model = UserProfileInfo
         fields = ('portfolio_site','profile_pic')

class UploadFileForm(forms.Form):
    file = forms.FileField()

dappx/views.py
from django.shortcuts import render

# Create your views here.
from dappx.forms import UserForm,UserProfileInfoForm,UploadFileForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from dappx.models import LogFile 
from django.contrib.auth.models import User

import os.path as op
import os
import time

@login_required
def index(request):
    if request.method == 'GET':
        # current_user = request.user
        username = User.objects.get(username=request.user)
        logs = LogFile.objects.filter(PostedBy = username)
        context = {
                "logs": logs
                 }
        return render(request,'dappx/index.html', context)

    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            saved_path = handle_uploaded_file(request.user, request.FILES['file'])
        else:
            return HttpResponse(status=500)

        username = User.objects.get(username=request.user)
        logObj = LogFile.objects.create(
                            LogPath = saved_path,
                            FileName = request.FILES['file'].name,
                            PostedBy = username)
        logObj.save()
        return render(request,'dappx/index.html')


def handle_uploaded_file(user, f):
    file_center = "/home/haihuam/Projects/dprojx/uploadfiles/"
    user_file_dir = op.join(file_center, str(user))
    if not op.exists(user_file_dir):
        try: 
            os.makedirs(user_file_dir)
        except:
            # Directories created failed.
            return 

    file_name = "_".join([str(int(time.time())), f.name])
    file_save_path = op.join(user_file_dir, file_name)

    with open(file_save_path, 'wb+') as destination:
        for chunk in f.chunks():
            destination.write(chunk)

    return file_save_path

@login_required
def special(request):
    return HttpResponse("You are logged in !")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        # profile_form = UserProfileInfoForm(data=request.POST)
        if user_form.is_valid() :
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            registered = True
        else:
            # print(user_form.errors,profile_form.errors)
            print(user_form.errors)
    else:
        user_form = UserForm()
        # profile_form = UserProfileInfoForm()
    return render(request,'dappx/registration.html',
                          {'user_form':user_form,
                           'registered':registered})

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        # print(username, password)
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Your account was inactive.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details given")
    else:
        return render(request, 'dappx/login.html', {})

templates/dappx/bak.index.html
{% extends "dappx/base.html" %}
{% block body_block %}
<br>
<div class="container">
  <div class="jumbotron">
    <h4>Post a log file to start analyze!</h4>


<form method="POST" action="#" enctype="multipart/form-data">
   {% csrf_token %}
    <!-- COMPONENT START -->
    <div class="form-group">
        <div class="input-group input-file" name="Fichier1">
            <input type="text" class="form-control" placeholder='Choose a file...' />            
            <span class="input-group-btn">
                <button class="btn btn-default btn-choose" type="button">Choose</button>
            </span>
        </div>
    </div>
    <!-- COMPONENT END -->
    <div class="form-group">
        <button type="submit" class="btn btn-primary pull-right" >Submit</button>
        <button type="reset" class="btn btn-danger">Reset</button>
    </div>
</form>


  </div>

</div>
<script>
function bs_input_file() {
    $(".input-file").before(
        function() {
            if ( ! $(this).prev().hasClass('input-ghost') ) {
                var element = $("<input type='file' class='input-ghost' style='visibility:hidden; height:0'>");
                element.attr("name",$(this).attr("name"));
                element.change(function(){
                    element.next(element).find('input').val((element.val()).split('\\').pop());
                });
                $(this).find("button.btn-choose").click(function(){
                    element.click();
                });
                $(this).find("button.btn-reset").click(function(){
                    element.val(null);
                    $(this).parents(".input-file").find('input').val('');
                });
                $(this).find('input').css("cursor","pointer");
                $(this).find('input').mousedown(function() {
                    $(this).parents('.input-file').prev().click();
                    return false;
                });
                return element;
            }
        }
    );
}
$(function() {
    bs_input_file();
});

</script>



{% endblock %}

templates/dappx/base.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Log Analyze Platform - Login</title>

	{% load static %}
	<link rel="stylesheet" href="{% static "bootstrap-4.4.1-dist/css/bootstrap.min.css" %}">
	<script src="{% static "vendor/jquery/jquery.js"  %}"></script>
	<script src="{% static "bootstrap-4.4.1-dist/js/bootstrap.min.js" %}"></script>

</head>

  <body >

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Log Analyze Platform</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'index' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'dappx:register' %}">Register</a>
      </li>
      <li class="nav-item">
          {% if user.is_authenticated %}
        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
          {% else %}
        <a class="nav-link" href="{% url 'dappx:user_login' %}">Login</a>
          {% endif %}
      </li>
    </ul>
  </div>
</nav>

    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>

  <!-- Bootstrap core JavaScript-->
	<!-- <script src="{% static "vendor/jquery/jquery.min.js" %}"></script> -->
	<!-- <script src="{% static "vendor/bootstrap/js/bootstrap.bundle.min.js" %}"></script> -->

  <!-- Core plugin JavaScript-->
	<!-- <script src="{% static "vendor/jquery-easing/jquery.easing.min.js" %}"></script> -->

  <!-- Custom scripts for all pages-->
	<!-- <script src="{% static "js/sb-admin-2.min.js" %}"></script> -->

  </body>
</html>

templates/dappx/index.html
{% extends "dappx/base.html" %}
{% block body_block %}
<br>
<div class="container">
  <div class="jumbotron">
    <h4>Start from posting a log file.</h4>
<hr>

      <div class="form-group">
				<div class="input-group">
					<div class="input-group-prepend">
						<button type="button"  class="btn input-group-text btn-secondary" onclick="UploadFileFn()" id="upload-btn" disabled>Upload</button>
					</div>

					<div class="custom-file">
						<input type="file" class="custom-file-input" id="id_file" name="file" onchange="FileChangeFn(event)" aria-describedby="upload-btn">
						<label class="custom-file-label" for="inputGroupFile01">Choose file</label>
					</div>
				</div>

				<label class="label-default" id="file_size"></label> <label class="label-default" id="file_type"></label>
						<div id="file_box"></div>
								<div class="progress" >
									<div id="speed" class="progress-bar progress-bar-striped bg-info" role="progressbar" style="width: 0%" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100"></div>
								</div>
        </div>
  </div>

<table class="table">
  <thead class="thead-light">
    <tr>
      <th scope="col">File </th>
      <th scope="col">Post Time</th>
      <th scope="col">Operation</th>
    </tr>
  </thead>
  <tbody>
    {% for log in logs %}
    <tr>
      <th scope="row">{{ log.FileName }} </th>
      <td>{{ log.PostedDate }}</td>
      <td></td>
    </tr>
   {% endfor %}
  </tbody>
</table>



</div>

<script>
var uploadUrl = '/';
//文件选择完毕时
function FileChangeFn(event) {
    $('.opst_txt').text('Please reselect the file.');
		$('#upload-btn').prop('disabled', false);
    $("#upload-btn").removeClass('btn-secondary');
    $("#upload-btn").addClass('btn-primary');
    var event = event || window.event,
        dom = '',
        ofile = $("#id_file").get(0).files[0],
        otype = ofile.type || 'File type access failed.',
        osize = ofile.size / 1054000,
        ourl = window.URL.createObjectURL(ofile); 
    $('#file_type').text("File Type：" + otype);
    $('#file_size').text("Size: " + osize.toFixed(2) + "MB.");

    $('#file_box').html(dom);
};

function OnProgRess(event) {
    var event = event || window.event;
    var loaded = Math.floor(100 * (event.loaded / event.total)); 
    $("#speed").html(loaded + "%").css("width", loaded + "%");
};


function UploadFileFn() {

    $('.progress').show();
    var oFile = $("#id_file").get(0).files[0], 
        formData = new FormData(); 
    xhr = $.ajaxSettings.xhr(); 
    formData.append("file", oFile); 
	  formData.append('csrfmiddlewaretoken', '{{ csrf_token }}');
		console.log(formData);
    $.ajax({
        type: "POST",
        url: uploadUrl, 
        data: formData, 
        cache: false, 
        async: true, 
        processData: false, 
        contentType: false,
        xhr: function() {
            if (OnProgRess && xhr.upload) {
                xhr.upload.addEventListener("progress", OnProgRess, false);
                return xhr;
            }
        },
        success: function(returndata) {
            $("#speed").removeClass('bg-info');
            $("#speed").addClass('bg-success');
            $("#speed").html("Submit Success");
					  // location.reload();
        },
        error: function(returndata) {
            $("#speed").html("Submit Failed");
            console.log(returndata)
        }
    });

		$('#upload-btn').prop('disabled', true);
    $("#upload-btn").removeClass('btn-primary');
    $("#upload-btn").addClass('btn-secondary');
};

</script>

{% endblock %}

templates/dappx/login.html
{% extends 'dappx/base.html' %}
{% block body_block %}

    <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-10 col-lg-12 col-md-9">

        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-5">
            <!-- Nested Row within Card Body -->
            <div class="row">
              <!-- <div class="col-lg-6 d-none d-lg-block bg-login-image"></div> -->
              <div class="col-lg-6">
                <div class="p-5">
                  <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">Welcome Back!</h1>
                  </div>
                  <form class="user" method="post">
									  {% csrf_token %}

                    <div class="form-group">
                      <input type="text" name="username" class="form-control form-control-user" required id="username"  placeholder="Enter User Name...">
                      <input type="password" name="password" class="form-control form-control-user"  required id="password" placeholder="Password"  >
										</div>

                    <button class="btn btn-primary btn-user btn-block" type="submit">Login</button>

                  </form>
                  <hr>
                  <div class="text-center">
                    <a class="small" href="forgot-password.html">Forgot Password?</a>
                  </div>
                  <div class="text-center">
                    <a class="small" href="register.html">Create an Account!</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>

{% endblock %}

templates/dappx/registration.html
{% extends "dappx/base.html" %}
{% load static %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <!-- <h1>Register Here</h1> -->
        <!-- <h3>Just fill out the form.</h3> -->
<form enctype="multipart/form-data" method="POST">
          {% csrf_token %}

		<div class="form-group">
							
			<input type="text" name="username" class="form-control form-control-user" required id="id_username"  placeholder="User Name">
			<input type="password" name="password" class="form-control form-control-user"  required id="id_password" placeholder="Password"  >
			<input type="email" name="email" maxlength="254" class="form-control form-control-user"  id="id_email" placeholder="Email">
		</div>
          <!-- <input type="submit" name="" value="Register"> -->
					<button class="btn btn-primary btn-user btn-block" type="submit">Register</button>
</form>
        
      {% endif %}
    </div>
  </div>
{% endblock %}

templates/dappx/retired.html
{% extends 'base.html' %}

{% block title %}Sign Up{% endblock %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}

templates/dappx/temp.login.html
{% extends 'dappx/base.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1>Login here :</h1>
<form method="post" action="{% url 'dappx:user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">
<label for="password">Password:</label>
          <input type="password" name="password" placeholder="Password">
<input type="submit" name="" value="Login">
</form>
</div>
  </div>
{% endblock %}